### ISSUE TITLE
how to plot the float entropy run dynamic.py error KeyError: 'val/entropy_layer_02'

### ISSUE THREAD

**Issue by donggeai** [OrangeBai/APCT-master#5]
I have run the latest train process by `python train.py --dataset cifar10 --net vgg16 --project expressive --name split_0.1 --num_step 240 --val_step 120 -train_mode exp --split 0.1`， and the run dynamic.py to generate the float entropy plot, but error as follows:
```python
Traceback (most recent call last):
  File "dynamic.py", line 35, in <module>
    yy = np.array(list(pd_10[name])).T
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'val/entropy_layer_02'
```
How can I solve it and get the float entroy plot? Thanks.

**Comment by OrangeBai** [comment]
Hi, have you installed [wandb](https://wandb.ai/site) and uploaded the training results to the remote?
